### ISSUE TITLE
Make crossplatform Chrome finder

### ISSUE THREAD

**Issue by Sicos1977** [Sicos1977/ChromeHtmlToPdf#14]

**Comment by nicolasr75** [comment]
Ok, I'm going to submit a pull request with a ChromeFinder class in the next days.
Nicolas

**Comment by nicolasr75** [comment]
I have a first working version of a ChromeFinder class for you to review. Unfortunately I am not that familiar with Github. Can you give me some instructions on how to proceed? The Github docs say I would have to create a new branch, commit my changes and then create a pull request. But how do I create a branch in your repository? Or do I have to fork everything to my own account?

**Comment by Sicos1977** [comment]
You need to clone my repository and then make changes in your cloned repository and when done make a pull request for me. But if you find that to difficult you can also just send me the cs file (sicos2002@hotmail.com)

**Comment by nicolasr75** [comment]
Ok, since it's just a single file, I send it via e-mail.

Some comments about it:

- I can currently not test OSX because I have none
- Linux distros are of course too many to test them all. What I have tested is Linux Raspian ARM, Linux Mate ARM and Debian x64
- I have kept the access to the registry under Windows. For this to work in a .NET Core project you need the Windows Compatibility Nuget package. It doesn't do any harm to keep that code under Linux as long as it is wrapped in a runtime OS detection as you can see in my code
- Although there is a Chrome x64 version, Google decided to keep the default installation directory under Windows in Program Files x86 and the same for the registry key. Very confusing, if you ask me. So we are fine with a single registry key now but who knows what the future brings.
- It is unclear what to do if both Chrome and Chromium are installed. It would depend on the order in the list of exe names but also on the specific installation directory. For default installations Chrome should be found first

**Comment by Sicos1977** [comment]
Implemented with commit f8af8ac51dfdd8ebcdf16f1ca6fdb143d75d70a9
