### ISSUE TITLE
How to convert html string to Pdf

### ISSUE THREAD

**Issue by umar-ulabs** [Sicos1977/ChromeHtmlToPdf#44]
How to convert html as string to pdf  instead of from ConvertUri?
 Thanks

**Comment by brunoinds** [comment]
I know it is not the answer you want, but a workaround is to create a Temp file `.html` and pass the path as a parameter. Because I think, the `chrome.exe` machine receives the path and exports the `PDF ` as a file, and not as base64 or something else. You can create a Temp folder and add the `.html` files on it and receive the `PDF` files from the converter. After your code execution, delete the temp folder.

**Comment by Sicos1977** [comment]
Well it is possible to use html but I just did not program it that way.

**Comment by Sicos1977** [comment]
I just released a new nuget package for this.

https://www.nuget.org/packages/ChromeHtmlToPdf
