### ISSUE TITLE
How to obtain the html source code of each page after paging according to the width and height

### ISSUE THREAD

**Issue by ClarkSmiths** [Sicos1977/ChromeHtmlToPdf#74]

**Comment by Sicos1977** [comment]
I don't understand exactly what you want to do?

**Comment by Sicos1977** [comment]
If you just want a snapshot of the page then you can set the CaptureSnapshot to true. This will produce a snapshot of the page as a .mhtml file. If you have used the convert method with a stream as output then the snapshot is written to the SnapshotStream property otherwise it is written to the same location as where you are placing the converted pdf file.
